name: in_app_devtools
description: "In app devtools."
version: 0.0.2

environment:
  sdk: ^3.6.0
  flutter: ">=3.20.0"

dependencies:
  flutter:
    sdk: flutter
  provider: '>=5.0.0 <7.0.0'
  path_provider: ^2.0.0
  dio: ^5.0.0
  uuid: ^4.0.0
  intl: '>=0.18.0 <0.20.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.  
# flutter:
