name: in_app_devtools
description: "In app devtools."
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ">=3.20.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  path_provider: ^2.1.5
  dio: ^5.0.0
  uuid: ^4.5.1
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.  
# flutter:
